ProjectSC/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landingpage.urls')),
    path('diabetes/', include('diabetes.urls')),
]

diabetes/urls.py
from django.urls import path
from diabetes import views


app_name = 'diabetes'

urlpatterns = [
    path('information', views.information, name = "information"),
    path('anyIdea', views.anyIdea, name = "anyIdea"),
    path('result', views.result, name = "result"),
    path('about', views.about, name = "about"),
    path('treatment', views.treatment, name = "treatment")
]

landingpage/urls.py
from django.urls import path
from landingpage import views

app_name = 'landing'

urlpatterns = [
    path('', views.index, name = "landingpage")
]

diabetes/models.py
from django.db import models

# Create your models here.

landingpage/models.py
from django.db import models

# Create your models here.

diabetes/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .obesity import *
from .bayesian2 import *



def information(request):
    return render(request, 'Information.html')

def anyIdea(request):
    return render(request, 'anyIdea.html')

def treatment(request):
    return render(request, 'treatment.html')
    
def about(request):
    return render(request, 'about.html')
	
def result(request):
	if request.method == 'POST':
		gender = request.POST['gender']
		smoker = request.POST['smoker']
		age = request.POST['usia']
		tinggi = request.POST['tinggi']
		berat = request.POST['berat']

		givenSet = set()
		

		if (gender != "Unknown"):
			if (gender == "Pria"):
				givenSet.add("G")
			else:
				givenSet.add("nG")
	
		
		if (smoker != "Unknown"):
			if (smoker == "Ya"):
				givenSet.add("S")
			else:
				givenSet.add("nS")

		if(tinggi != "" and berat != ""):
			if(isObesity(int(tinggi),int(berat))):
				givenSet.add("O")
			else:
				givenSet.add("nO")


		if (age != ""):
			if (int(age) < 44):
				givenSet.add("1")
			elif (int(age) >= 44 and int(age) < 65 ):
				givenSet.add("2")
			else:
				givenSet.add("3")
		
		# print(givenSet)
		result = inference("D",givenSet)
		# print(result)
		# result = hitung1(smokerSym, genderSym, obesitySym,ageSym)
		finalResult = round(result * 100,2)
		return render(request, 'Result.html', {"result" : finalResult})

landingpage/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect

# Create your views here.


def index(request):
    return render(request, 'landingPage.html')

diabetes/templates/Information.html
{% extends 'base.html'%}
{% load static %}
{% block content %}
  
  <div class="row" style="height: 50px;">
  </div>
  <div class="row d-flex justify-content-between align-items-center">
    <div class="col-3">
    </div>
    <div class="col-7">
      <div class="row d-flex justify-content-between align-items-center">
        <div class="kotak-tes-diabetes">
          <div class="row" style="margin-left: 20px; margin-top:15px;">
            <div class="col-4">
              <p class="judul">INFORMATION</p>
              <div class="row" style="height: 1px; background-color: #EBB244;"></div>
            </div>
            <div class="col-4">
              <p class="judul">RESULT</p>
            </div>
            <div class="col-4">
              <p class="judul">TREATMENT</p>
            </div>
          </div>
          <div class="row" style="height: 1px; width: 700px; background-color: #E1CDCD; margin-left: 0px;"></div>
          <div class="row" style="margin-left: 80px; margin-top:30px;">
            <div class="col-10">
              <div class="row" style="margin-top: 10px;">
                <form action="{% url 'diabetes:result' %}" method="POST">
                  {% csrf_token %}
                  <div id="gender">
                    <span style="padding-right: 15px;">Jenis Kelamin : </span>
                    <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" name="gender" id="jenis-kelamin" value="Pria">
                      <label class="form-check-label" for="exampleRadios1">
                        Pria
                      </label>
                    </div>
                    <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" name="gender" id="jenis-kelamin" value="Wanita">
                      <label class="form-check-label" for="exampleRadios2">
                        Wanita
                      </label>
                    </div>
                    <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" name="gender" id="jenis-kelamin" value="Unknown" checked>
                      <label class="form-check-label" for="exampleRadios3">
                        Memilih Tidak Menjawab
                      </label>
                    </div>
                  </div>
                  <br>
                  <div id="smoker">
                    <span style="padding-right: 15px;">Apakah anda perokok? : </span>
                    <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" name="smoker" id="smoker" value="Ya">
                      <label class="form-check-label" for="exampleRadios4">
                        Ya
                      </label>
                    </div>
                    <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" name="smoker" id="smoker" value="Tidak">
                      <label class="form-check-label" for="exampleRadios5">
                        Tidak
                      </label>
                    </div>
                    <div class="form-check form-check-inline">
                      <input class="form-check-input" type="radio" name="smoker" id="Smoker" value="Unknown" checked>
                      <label class="form-check-label" for="exampleRadios6">
                        Memilih tidak menjawab
                      </label>
                    </div>
                  </div>
                  <br>
                  <div id="bmi">
                    <div class="row">
                      <div class="col-4">
                        <label>Tinggi Badan : </label>
                      </div>
                      <div class="col-5">
                        <input type="number" class="form-control" placeholder="contoh: 170" name="tinggi">
                      </div>
                      <div class="col"><label>cm</label></div>
                    </div>
                    <br>
                    <div class="row">
                      <div class="col-4">
                        <label>Berat Badan : </label>
                      </div>
                      <div class="col-5">
                        <input type="number" class="form-control" placeholder="contoh: 44" name="berat">
                      </div>
                      <div class="col"><label>kg</label></div>
                    </div>
                  </div>
                  <br>
                  <div id="usia">
                    <div class="row">
                      <div class="col-4">
                        <label>Usia : </label>
                      </div>
                      <div class="col-5">
                        <input type="number" class="form-control" placeholder="contoh: 19" name="usia">
                      </div>
                      <div class="col"><label>tahun</label></div>
                    </div>
                  </div>
                  <br>
                  <div class="row">
                    <div class="col-5"></div>
                    <div class="col-6">
                        <button type="submit" class="btn btn-default button-submit">Submit</button>
                    </div>
                    <div class="col-1"></div>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  {% endblock content %}

diabetes/templates/Result.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

  <div class="row" style="height: 50px;">
  </div>
  <div class="row d-flex justify-content-between align-items-center">
    <div class="col-3">
    </div>
    <div class="col-7">
      <div class="row d-flex justify-content-between align-items-center">
        <div class="kotak-tes-diabetes">
          <div class="row" style="margin-left: 20px; margin-top:15px;">
            <div class="col-4">
              <p class="judul">INFORMATION</p>
            </div>
            <div class="col-4">
              <p class="judul">RESULT</p>
              <div class="row" style="height: 1px; background-color: #EBB244;"></div>
            </div>
            <div class="col-4">
              <p class="judul">TREATMENT</p>
            </div>
          </div>
          <div class="row" style="height: 1px; width: 700px; background-color: #E1CDCD; margin-left: 0px;"></div>
          <div class="row" style="margin-left: 50px; margin-top:10px;">
            <div class="col-8">
              <div class="row" style="margin-top: 30px;">
                <p class = "resultHeader">Kemungkinan Persentase Diabetes:</p>
              </div>
            </div>
          </div>
          <div class = "text-center result"> <p><font color= "#EBB244">  {{ result }}%</font></p></div>

          <div class="row" style="margin-left: 50px; margin-top:100px;">
              <div class="col-5"> <p class = "keterangan">*Keterangan: Jika ada keluarga dekat Anda menderita diabetes, persentase Anda akan tambah 10x lipat.</p> </div>
              <div class = "col-7">
                <div class = "text-center"> 
                    <a class = "text-right"  href = "{% url 'diabetes:treatment' %}"><button class = "btn btn-default button-submit">Selanjutnya</button></a> 
                </div>
                

              </div>
              
            
          </div>

          
        </div>
      </div>
    </div>
  </div>
  {% endblock content %}

diabetes/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row" style="height: 50px;">
</div>
<div class="row d-flex justify-content-between align-items-center">
  <div class="col-3">
  </div>
  <div class="col-7">
    <div class="row d-flex justify-content-between align-items-center">
      <div class="kotak-tes-diabetes">
        <div class="row" style="margin-left: 20px; margin-top:15px;">
          <div class="col-4">
            <p class="judul">About</p>
            <div class="row" style="height: 1px; background-color: #EBB244;"></div>
          </div>
          <div class="row" style="margin-left: 1px; margin-top:40px;"> 
            <div class="col-8" style="width: 1000px;"> 

              <p style="text-align: justify;">
              Berawal dari kekhawatiran kami yang menyadari bahwa pentingnya pengetahuan tentang
              diabetes sejak dini, kami membuat simulator pengecekkan diabetes sederhana. 
              Namun, mohon jangan jadikan simulator kami sebagai acuan ya! Terima kasih dan
              selamat mencoba SeberapaManisKamu?</p>
              
            </div>
            
          
          </div>
            
            
          

              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock content %}

diabetes/templates/anyIdea.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row" style="height: 50px;">
  </div>
  <div class="row d-flex justify-content-between align-items-center">
    <div class="col-3">
    </div>
    <div class="col-7">
      <div class="row d-flex justify-content-between align-items-center">
        <div class="kotak-tes-diabetes">
          <div class="row" style="margin-left: 20px; margin-top:15px;">
            <div class="col-4">
              <p class="judul"> Saran untuk kami?</p>
              <div class="row" style="height: 1px; background-color: #EBB244;"></div>
            </div>
            <div class="container" style="margin-top:  80px; margin-left: 20px;">
              <h4>Kritik dan saran dari kalian akan sangat berarti!</h4>
              <form class="form-horizontal" action="/action_page.php">
                <div class="form-group">
                  <label class="control-label col-sm-2" for="typehere">Ketik disini:</label>
                  <div class="col-sm-10">
                    <input type="email" class="form-control" id="email" placeholder="Saranku...." name="email">
                  </div>
                </div>
                
                <div class="form-group">        
                  <div class="col-sm-offset-2 col-sm-10">
  
                  </div>
                </div>
                
                <div class="form-group">        
                  <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-default">Submit</button>
                  </div>
                </div>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

diabetes/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>SeberapaManisKamu - Diabetes</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel = "stylesheet" type = "text/css" href = "{% static 'css/diabetes.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Handlee&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato:400i|Roboto" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Handlee&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Courgette&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Domine|Oswald&display=swap" rel="stylesheet">
  

</head>


<body>
  <div class="row">
    <div class="col-3">
    </div>
    <div class="col-7">
    </div>
  </div>
  <nav class="navbar navbar-expand-lg navbar-light bg-white">
    <a class="navbar-brand" href="{% url 'landing:landingpage' %}" style="font-family:'Handlee', cursive; font-size: 28px;">Seberapa</a>
    <a class="navbar-brand" href="{% url 'landing:landingpage' %}" style="font-family:'Courgette', cursive; font-size: 28px; color:#EBB244;">Manis</a>
    <a class="navbar-brand" href="{% url 'landing:landingpage' %}" style="font-family:'Handlee', cursive; font-size: 28px;">Kamu</a>
    <a href="#"><img src="{% static 'images/faq.png' %}" height="40px;" width="40px;"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end"  id="navbarNav">
      <ul class="navbar-nav">
        <li style="float:right">
          <a class="nav-link" href="{% url 'diabetes:anyIdea' %}" style="color: black; font-family: 'Roboto', sans-serif; font-size: 16px; font-weight: bold;">ANY IDEA?<span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'diabetes:about' %}" style="color: black; font-family: 'Roboto', sans-serif; font-size: 16px; font-weight: bold;">ABOUT</a>
        </li>
      </ul>
    </div>
  </nav>
  <div id="site-wrapper">
      {% block content %}
      {% endblock content %}

  </div>
</body>

</html>

diabetes/templates/treatment.html
{% extends 'base.html'%}
{% load static %}
{% block content %}

  <div class="row" style="height: 50px;">
  </div>
  <div class="row d-flex justify-content-between align-items-center">
    <div class="col-3">
    </div>
    <div class="col-7">
      <div class="row d-flex justify-content-between align-items-center">
        <div class="kotak-tes-diabetes">
          <div class="row" style="margin-left: 20px; margin-top:15px;">
            <div class="col-4">
              <p class="judul">INFORMATION</p>
            </div>
            <div class="col-4">
              <p class="judul">RESULT</p>
              
            </div>
            <div class="col-4">
              <p class="judul">TREATMENT</p>
              <div class="row" style="height: 1px; background-color: #EBB244; width: 180px; margin-left: 10px"></div>
            </div>
          </div>
          <div class="row" style="height: 1px; width: 700px; background-color: #E1CDCD; margin-left: 0px;"></div>
          <div class="row" style="margin-left: 50px; margin-top:30px;">
            <h2 style="font-family: 'Roboto'; font-size: 22px; font-weight: bold;">Positif Diabetes</h2>
          </div>
          <div class ="row" style="margin-left: 50px; margin-top:10px;">
                <ul>
                        <li>Cek untuk kondisi lebih lanjut ke dokter terdekat.</li>
                        <li>Ubah pola makan, kurangin gula pada makanan, dan perbanyak buah dan sayur.</li>
                        <li>Rajin berolahraga.</li>
                        <li>Pilih alas kaki yang sesuai agar tidak gampang luka</li>
                        <li>Jaga kebersihan mulut agar mulutnya tidak kena infeksi.</li>


                </ul>  
        </div>

        <div class="row" style="margin-left: 50px; margin-top:20px;">
                <h2 style="font-family: 'Roboto'; font-size: 22px; font-weight: bold;">Mengurangi Terjadinya Diabetes</h2>
        </div>
        <div class ="row" style="margin-left: 50px; margin-top:10px;">
                <ul>
                        <li>Batasi makan daging merah.</li>
                        <li>Hindari minuman manis.</li>
                        <li>Kalo bisa makan karbo whole grain daripada grafined grain</li>


                </ul>  
        </div>

          
        </div>
      </div>
    </div>
  </div>
  {% endblock content %}

landingpage/templates/landingPage.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>SeberapaManisKamu</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <link rel = "stylesheet" type = "text/css" href = "{% static 'main.css' %}">
  <link href="https://fonts.googleapis.com/css?family=Handlee&display=swap" rel="stylesheet">
  

</head>


<body>
  <div class="landing-page2">
      <div class="landing-page-content">
          <h1 class = "name">Seberapa <font color= "#EBB244">Manis</font> Kamu <img src="{% static 'images/faq.png' %}" height="50px;" width="50px;"></h1>
          <div class= "button-position">
              <a href = "{% url 'diabetes:information' %}"><button class = "button-design">Tes Sekarang</button></a>
          </div>
          
      </div>
  </div>
 
</body>

</html>